swagger: '2.0'
info:
  x-ibm-name: accounts
  title: Accounts
  version: 1.0.0
schemes:
  - https
basePath: /accounts
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - map:
          title: 'getBalance: input'
          inputs:
            customer_id:
              schema:
                type: double
              variable: request.parameters.customer_id
          outputs:
            body:
              schema:
                $ref: '#/x-ibm-configuration/targets/AccountService/definitions/getBalanceInput'
              variable: message.body
              content: application/xml
            content-type:
              schema:
                type: string
              variable: message.headers.content-type
            SOAPAction:
              schema:
                type: string
              variable: message.headers.SOAPAction
          actions:
            - set: content-type
              default: text/xml
            - set: SOAPAction
              default: getBalance
            - set: body.Envelope.Body.getBalance.arg0
              from: customer_id
      - invoke:
          title: 'getBalance: invoke'
          target-url: 'http://banka.mybluemix.net/services/AccountService'
          timeout: 60
          verb: POST
          cache-response: protocol
          cache-ttl: 900
          output: getBalanceOut
      - map:
          title: 'getBalance: output'
          inputs:
            input:
              schema:
                $ref: '#/x-ibm-configuration/targets/AccountService/definitions/getBalanceOutput'
              variable: getBalanceOut.body
              content: application/xml
          outputs:
            balance:
              schema:
                $ref: '#/definitions/Account Output'
              variable: message.body
          actions:
            - set: balance.Balance
              from: input.Envelope.Body.getBalanceResponse.return
    catch: []
  phase: realized
  targets:
    AccountService:
      swagger: '2.0'
      info:
        title: AccountService
        description: ''
        x-ibm-name: accountservice-1
        version: 1.0.0
      schemes:
        - https
      basePath: /AccountService
      produces:
        - application/xml
      consumes:
        - text/xml
      securityDefinitions:
        clientID:
          type: apiKey
          name: X-IBM-Client-Id
          in: header
          description: ''
      security:
        - clientID: []
      x-ibm-configuration:
        type: wsdl
        wsdl-definition:
          wsdl: 595a0e4a0cf2c7204fd53aa5
          service: AccountService
          port: AccountPort
          soap-version: '1.1'
        assembly:
          execute:
            - proxy:
                title: proxy
                target-url: 'http://banka.mybluemix.net/services/AccountService'
        gateway: datapower-gateway
        enforced: true
        testable: true
        phase: realized
        cors:
          enabled: true
      paths:
        /getBalance:
          post:
            summary: Operation getBalance
            description: ''
            operationId: getBalance
            x-ibm-soap:
              soap-action: getBalance
              soap-operation: '{http://bankA.sample.ibm.com/}getBalance'
            parameters:
              - in: body
                name: body
                required: true
                schema:
                  $ref: '#/x-ibm-configuration/targets/AccountService/definitions/getBalanceInput'
            responses:
              default:
                description: ''
                schema:
                  $ref: '#/x-ibm-configuration/targets/AccountService/definitions/getBalanceOutput'
      definitions:
        Security:
          xml:
            namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
            prefix: wsse
          type: object
          properties:
            UsernameToken:
              xml:
                namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
                prefix: wsse
              type: object
              properties:
                Username:
                  xml:
                    namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
                    prefix: wsse
                  type: string
                Password:
                  xml:
                    namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
                    prefix: wsse
                  type: string
                Nonce:
                  xml:
                    namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
                    prefix: wsse
                  type: string
                  properties:
                    EncodingType:
                      xml:
                        namespace: ''
                        attribute: true
                      type: string
                Created:
                  xml:
                    namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'
                    prefix: wsu
                  type: string
            Timestamp:
              xml:
                namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'
                prefix: wsu
              type: object
              properties:
                Created:
                  xml:
                    namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'
                    prefix: wsu
                  type: string
                Expires:
                  xml:
                    namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'
                    prefix: wsu
                  type: string
                Id:
                  xml:
                    namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'
                    prefix: wsu
                    attribute: true
                  type: string
        getBalanceInput:
          type: object
          properties:
            Envelope:
              xml:
                prefix: soap-env
                namespace: 'http://schemas.xmlsoap.org/soap/envelope/'
              type: object
              properties:
                Header:
                  $ref: '#/x-ibm-configuration/targets/AccountService/definitions/getBalanceHeader'
                Body:
                  type: object
                  properties:
                    getBalance:
                      $ref: '#/x-ibm-configuration/targets/AccountService/definitions/getBalance_tns'
                  required:
                    - getBalance
              required:
                - Body
          required:
            - Envelope
          example: >-
            <soap-env:Envelope
            xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">

             <soap-env:Header>

              <wsse:Security
            xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
            xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">

               <wsse:UsernameToken>

                <wsse:Username>string</wsse:Username>

                <wsse:Password>string</wsse:Password>

                <wsse:Nonce EncodingType="string">string</wsse:Nonce>

                <wsu:Created>string</wsu:Created>

               </wsse:UsernameToken>

               <wsu:Timestamp wsu:Id="string">

                <wsu:Created>string</wsu:Created>

                <wsu:Expires>string</wsu:Expires>

               </wsu:Timestamp>

              </wsse:Security>

             </soap-env:Header>

             <soap-env:Body>

              <tns:getBalance xmlns:tns="http://bankA.sample.ibm.com/"><!--
            mandatory -->

               <arg0><!-- mandatory -->3</arg0>

              </tns:getBalance>

             </soap-env:Body>

            </soap-env:Envelope>
        getBalanceHeader:
          type: object
          properties:
            Security:
              $ref: '#/x-ibm-configuration/targets/AccountService/definitions/Security'
        getBalanceOutput:
          type: object
          properties:
            Envelope:
              xml:
                prefix: soap-env
                namespace: 'http://schemas.xmlsoap.org/soap/envelope/'
              type: object
              properties:
                Body:
                  type: object
                  properties:
                    getBalanceResponse:
                      $ref: '#/x-ibm-configuration/targets/AccountService/definitions/getBalanceResponse_tns'
              required:
                - Body
          required:
            - Envelope
          example: >-
            <soap-env:Envelope
            xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">

             <soap-env:Body>

              <tns:getBalanceResponse xmlns:tns="http://bankA.sample.ibm.com/">

               <return><!-- mandatory -->3</return>

              </tns:getBalanceResponse>

             </soap-env:Body>

            </soap-env:Envelope>
        getBalance_tns:
          xml:
            namespace: 'http://bankA.sample.ibm.com/'
            prefix: tns
          type: object
          properties:
            arg0:
              type: integer
              format: int32
              xml:
                namespace: ''
                prefix: ''
          required:
            - arg0
          example: |-

            <tns:getBalance xmlns:tns="http://bankA.sample.ibm.com/">
             <arg0><!-- mandatory -->3</arg0>
            </tns:getBalance>
        getBalanceResponse_tns:
          xml:
            namespace: 'http://bankA.sample.ibm.com/'
            prefix: tns
          type: object
          properties:
            return:
              type: integer
              format: int32
              xml:
                namespace: ''
                prefix: ''
          required:
            - return
          example: |-

            <tns:getBalanceResponse xmlns:tns="http://bankA.sample.ibm.com/">
             <return><!-- mandatory -->3</return>
            </tns:getBalanceResponse>
  gateway: datapower-gateway
paths:
  /balance:
    get:
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/Account Output'
      parameters:
        - name: customer_id
          type: string
          required: true
          in: query
definitions:
  Account Output:
    properties:
      Balance:
        type: number
        format: double
    additionalProperties: false
    required:
      - Balance
tags: []
