swagger: '2.0'
info:
  title: AccountService
  description: ''
  x-ibm-name: accountservice
  version: 1.0.0
schemes:
  - https
basePath: /AccountService
produces:
  - application/xml
consumes:
  - text/xml
securityDefinitions:
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    description: ''
security:
  - clientID: []
x-ibm-configuration:
  type: wsdl
  wsdl-definition:
    wsdl: accountservice_1.0.0.wsdl
    service: AccountService
    port: AccountPort
    soap-version: '1.1'
  assembly:
    execute:
      - proxy:
          title: proxy
          target-url: 'http://banka.mybluemix.net/services/AccountService'
  gateway: datapower-gateway
  enforced: true
  testable: true
  phase: realized
  cors:
    enabled: true
paths:
  /getBalance:
    post:
      summary: Operation getBalance
      description: ''
      operationId: getBalance
      x-ibm-soap:
        soap-action: getBalance
        soap-operation: '{http://bankA.sample.ibm.com/}getBalance'
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/getBalanceInput'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/getBalanceOutput'
definitions:
  Security:
    xml:
      namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
      prefix: wsse
    type: object
    properties:
      UsernameToken:
        xml:
          namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
          prefix: wsse
        type: object
        properties:
          Username:
            xml:
              namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
              prefix: wsse
            type: string
          Password:
            xml:
              namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
              prefix: wsse
            type: string
          Nonce:
            xml:
              namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd'
              prefix: wsse
            type: string
            properties:
              EncodingType:
                xml:
                  namespace: ''
                  attribute: true
                type: string
          Created:
            xml:
              namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'
              prefix: wsu
            type: string
      Timestamp:
        xml:
          namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'
          prefix: wsu
        type: object
        properties:
          Created:
            xml:
              namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'
              prefix: wsu
            type: string
          Expires:
            xml:
              namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'
              prefix: wsu
            type: string
          Id:
            xml:
              namespace: 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd'
              prefix: wsu
              attribute: true
            type: string
  getBalanceInput:
    type: object
    properties:
      Envelope:
        xml:
          prefix: soap-env
          namespace: 'http://schemas.xmlsoap.org/soap/envelope/'
        type: object
        properties:
          Header:
            $ref: '#/definitions/getBalanceHeader'
          Body:
            type: object
            properties:
              getBalance:
                $ref: '#/definitions/getBalance_tns'
            required:
              - getBalance
        required:
          - Body
    required:
      - Envelope
    example: >-
      <soap-env:Envelope
      xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">

       <soap-env:Header>

        <wsse:Security
      xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
      xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">

         <wsse:UsernameToken>

          <wsse:Username>string</wsse:Username>

          <wsse:Password>string</wsse:Password>

          <wsse:Nonce EncodingType="string">string</wsse:Nonce>

          <wsu:Created>string</wsu:Created>

         </wsse:UsernameToken>

         <wsu:Timestamp wsu:Id="string">

          <wsu:Created>string</wsu:Created>

          <wsu:Expires>string</wsu:Expires>

         </wsu:Timestamp>

        </wsse:Security>

       </soap-env:Header>

       <soap-env:Body>

        <tns:getBalance xmlns:tns="http://bankA.sample.ibm.com/"><!-- mandatory
      -->

         <arg0><!-- mandatory -->3</arg0>

        </tns:getBalance>

       </soap-env:Body>

      </soap-env:Envelope>
  getBalanceHeader:
    type: object
    properties:
      Security:
        $ref: '#/definitions/Security'
  getBalanceOutput:
    type: object
    properties:
      Envelope:
        xml:
          prefix: soap-env
          namespace: 'http://schemas.xmlsoap.org/soap/envelope/'
        type: object
        properties:
          Body:
            type: object
            properties:
              getBalanceResponse:
                $ref: '#/definitions/getBalanceResponse_tns'
        required:
          - Body
    required:
      - Envelope
    example: >-
      <soap-env:Envelope
      xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">

       <soap-env:Body>

        <tns:getBalanceResponse xmlns:tns="http://bankA.sample.ibm.com/">

         <return><!-- mandatory -->3</return>

        </tns:getBalanceResponse>

       </soap-env:Body>

      </soap-env:Envelope>
  getBalance_tns:
    xml:
      namespace: 'http://bankA.sample.ibm.com/'
      prefix: tns
    type: object
    properties:
      arg0:
        type: integer
        format: int32
        xml:
          namespace: ''
          prefix: ''
    required:
      - arg0
    example: |-

      <tns:getBalance xmlns:tns="http://bankA.sample.ibm.com/">
       <arg0><!-- mandatory -->3</arg0>
      </tns:getBalance>
  getBalanceResponse_tns:
    xml:
      namespace: 'http://bankA.sample.ibm.com/'
      prefix: tns
    type: object
    properties:
      return:
        type: integer
        format: int32
        xml:
          namespace: ''
          prefix: ''
    required:
      - return
    example: |-

      <tns:getBalanceResponse xmlns:tns="http://bankA.sample.ibm.com/">
       <return><!-- mandatory -->3</return>
      </tns:getBalanceResponse>
