swagger: '2.0'
info:
  x-ibm-name: analytics
  title: analytics
  version: 0.0.1
schemes:
  - https
host: $(catalog.host)
basePath: /analytics/monitor
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - invoke:
          target-url: $(analytics-endpoint)
          verb: GET
          cache-response: no-cache
          password: password
          username: monitor
    catch: []
  phase: realized
  properties:
    analytics-endpoint:
      value: 'https://analyticsmonitor.eu-gb.mybluemix.net/api/autherrors?startTime=$(request.parameters.startTime)&endTime=$(request.parameters.endTime)&noOfCalls=$(request.parameters.threshold)&uriSegment=$(request.parameters.uriPath)&errorCode=$(request.parameters.errorCode)'
      description: NodeJs App
      encoded: false
paths:
  /:
    get:
      responses:
        '200':
          description: 200 Ok Unauthorised calls detected
          schema:
            $ref: '#/definitions/unauthorisedCalls'
        '204':
          description: 204 No Content
      operationId: get
      description: Get monitoring data about unauthorised calls
    parameters:
      - name: startTime
        type: string
        required: true
        in: query
        format: date-time
        description: Start Time for aggregation
      - name: endTime
        type: string
        required: true
        in: query
        description: End Time for aggregation
        format: date-time
      - name: threshold
        type: integer
        required: false
        in: query
        description: The number of unauthorised calls permitted in the date range. Default is 20
        format: int32
      - name: uriPath
        type: string
        required: true
        in: query
        description: The uri segment to filter on
      - name: errorCode
        type: string
        required: true
        in: query
        description: Error Code to filter on
definitions:
  unauthorisedCalls:
    type: array
    items:
      $ref: '#/definitions/unauthorisedCallSummary'
  unauthorisedCallSummary:
    properties:
      noOfCalls:
        type: integer
        format: int32
      apiName:
        type: string
      orgName:
        type: string
    additionalProperties: false
tags: []
