swagger: '2.0'
info:
  version: 1.0.0
  title: jwtAPI
  x-ibm-name: jwtapi
host: $(catalog.host)
basePath: /
paths:
  /validate-jwt:
    get:
      responses:
        '200':
          description: 200 OK
    parameters:
      - name: Authorization
        type: string
        required: true
        in: header
        description: 'Bearer <jwt-token>'
  /generate-jwt:
    get:
      responses:
        '200':
          description: 200 OK
    parameters:
      - name: iss-claim
        type: string
        required: true
        in: header
        description: Issuer claim
      - name: aud-claim
        type: string
        required: true
        in: header
        description: Audience claim
      - name: sub-claim
        type: string
        required: true
        in: query
securityDefinitions: {}
security: []
x-ibm-configuration:
  assembly:
    execute:
      - set-variable:
          title: set-variable
          actions:
            - value: '{ "alg": "HS256",   "kty": "oct",   "use": "sig",   "k": "ycsjclSb2dcdnJ-VobQLWeXBYUsFsPS8MddhqQ9N0d1CWWMms0FQH70SJQX2RcrTamhzyNniXtbLf47qDLJ6JI75oU-uUTHstpyzON1FQtpHIGajMaScIn4ZdT9pzgVwR7Ll1y_9wGBLeLW5Pqy0MhQDUO62BTB8hJ6CE8S9y4WwwrPD5Zj-jNDlSeZyAFnaa573SyITxwgDuMHgmIuKkt02ByWhS2mrTKCSOfdPIP_QdUPqbyixOji8A5fsoO65gAxzxvVfZNN4JgwHGRfllj5lH1nljL0MYlWGJ7i5iqvxp0-EAKgiHf8QsRWNXbpp03mGCXsz2XpnO6P9Kx7abw",   "kid": "hs256-key" }'
              add: hs256-key
      - switch:
          title: switch
          case:
            - condition: "((request.verb==='GET')&&(api.operation.path==='/generate-jwt'))"
              execute:
                - jwt-generate:
                    title: jwt-generate
                    jwt: generated-jwt
                    exp-claim: 3600000
                    version: 1.0.0
                    jws-alg: HS256
                    jti-claim: false
                    jws-jwk: hs256-key
                    iss-claim: request.headers.iss-claim
                    sub-claim: request.parameters.sub-claim
                    aud-claim: request.headers.aud-claim
                - gatewayscript:
                    title: gatewayscript
                    source: "apim.setvariable('message.body',apim.getvariable('generated-jwt'));   \n"
            - condition: "request.authorization.indexOf(\"Bearer\") > -1 && request.verb==='GET'&& api.operation.path==='/validate-jwt'"
              execute:
                - gatewayscript:
                    title: gatewayscript
                    source: >-
                      var authNode
                      = apim.getvariable('request.headers.authorization');



                      apim.setvariable('input-jwt', authNode.replace(/^Bearer /g,
                      ''));
                - jwt-validate:
                    title: jwt-validate
                    jwt: input-jwt
                    output-claims: decoded-claims
                    version: 1.0.0
                    iss-claim: eBusiness
                    aud-claim: TAPIv2
                    description: ''
                    jws-jwk: hs256-key
                - gatewayscript:
                    title: gatewayscript
                    source: "apim.setvariable('message.body',apim.getvariable('decoded-claims')); \n"
            - otherwise:
                - set-variable:
                    title: set-variable
                    actions:
                      - value: '302'
                        set: message.status.code
                      - set: message.status.reason
                        value: Found
                      - set: message.headers.Location
                        value: 'https://myidp.ibm.com'
    catch:
      - errors:
          - RuntimeError
        execute:
          - set-variable:
              title: set-variable
              actions:
                - value: '400'
                  set: message.status.code
                - set: message.status.reason
                  value: Bad request
          - gatewayscript:
              title: gatewayscript
              source: "apim.setvariable('message.body',apim.getvariable('jwt-validate.error-message'));   \n"
  enforced: true
  testable: true
  phase: realized
  cors:
    enabled: true
  gateway: datapower-gateway
schemes:
  - https
consumes:
  - application/json
  - application/xml
produces:
  - application/xml
  - application/json
  - a4b39561-7998-46a9-8d75-06d05c77efb0
