swagger: '2.0'
info:
  x-ibm-name: maptest
  title: MapTest
  version: 1.0.0
schemes:
  - https
host: $(catalog.host)
basePath: /maptest
consumes:
  - application/xml
  - application/json
produces:
  - application/json
  - application/xml
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - invoke:
          title: config-invoke
          timeout: 60
          verb: GET
          cache-response: no-cache
          cache-ttl: 900
          stop-on-error:
            - null
          version: 1.0.0
          target-url: 'https://0a16cbcf-ea89-475d-861a-4b4245404bda-bluemix.cloudant.com/config/shipping_rest_2_1'
          username: 0a16cbcf-ea89-475d-861a-4b4245404bda-bluemix
          password: 3ce292febfe64b6b34ec66b8a80cc2107e689fa7c75b971114a38770be61457c
          output: config
      - gatewayscript:
          title: gatewayscript
          version: 1.0.0
          source: |-



            var json = apim.getvariable("config");
            var endPoint = json.body.end_pont;
            var newJson = {"end" : endPoint};
            apim.setvariable('configEndPoint',  endPoint);

            apim.setvariable('message.body', newJson);
    catch: []
  phase: realized
paths:
  /map:
    put:
      responses:
        '200':
          description: 200 OK
      parameters:
        - name: api_parameter-1
          required: false
          in: body
          schema:
            type: object
definitions:
  unitCounters:
    type: array
    items:
      $ref: '#/definitions/unitCounter'
  unitCounter:
    properties:
      unit:
        type: string
      counter:
        type: string
    additionalProperties: false
  item:
    type: object
    properties:
      numberOfItems:
        type: string
      weight:
        type: string
    additionalProperties: true
  items:
    type: object
    properties:
      item:
        type: array
        items:
          $ref: '#/definitions/item'
    description: schema to hold array of single item structures
tags: []
