swagger: '2.0'
info:
  x-ibm-name: tapi-v2-browser
  title: TAPI v2 Browser
  version: 1.0.0
  description: 'Tracking API provides the functionality to enquire on the tracking status of mail items. The API provides the latest tracking information for single and multiple mail items, the tracking history for a single mail item, and the proof of delivery information (minus the signature image) for a single mail item.'
schemes:
  - https
host: api.royalmail.net
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - invoke:
          target-url: $(target-url)$(request.path)
  phase: realized
paths:
  '/myMailPieceIds/v2/{userId}':
    delete:
      responses:
        '200':
          description: 200 OK
      parameters:
        - name: userId
          type: string
          required: true
          in: path
          description: User identity
        - name: siteId
          type: string
          required: true
          in: query
          description: 'The siteId, used to distinguish between B2B and consumer'
        - name: mailPieceId
          type: string
          required: true
          in: query
          description: One or more tracking numbers of the mail item(s) to be deleted from the users saved list
        - $ref: '#/parameters/X-RMG-Auth-Token'
        - $ref: '#/parameters/X-RMG-Language'
        - $ref: '#/parameters/Origin'
      description: Delete from the list of recently tracked mailPieceIds for a specific user
    get:
      responses:
        '200':
          description: 200 OK
      parameters:
        - $ref: '#/parameters/X-RMG-Language'
        - $ref: '#/parameters/Origin'
        - $ref: '#/parameters/X-RMG-Auth-Token'
        - name: userId
          type: string
          required: true
          in: path
          description: User identity
        - name: siteId
          type: string
          required: true
          in: query
          description: 'The siteId, used to distinguish between B2B and consumer'
      description: Get list of recently tracked mailPieceIds for a specific user
  '/mailPieces/v2/{mailPieceId}/events':
    get:
      responses:
        '200':
          description: 200 OK
      parameters:
        - name: mailPieceId
          type: string
          required: true
          in: path
          description: A tracking number of the mail item being queried.
        - $ref: '#/parameters/X-RMG-Auth-Token'
        - $ref: '#/parameters/X-RMG-Language'
        - $ref: '#/parameters/Origin'
        - $ref: '#/parameters/X-recaptcha-session'
        - $ref: '#/parameters/X-recaptcha-response'
  '/mailPieces/v2/{mailPieceId}/signatureImage':
    get:
      responses:
        '200':
          description: 200 OK
      description: Get signature image for a mailPieceId
      parameters:
        - name: mailPieceId
          type: string
          required: true
          in: path
          description: A tracking number of the mail item being queried.
        - $ref: '#/parameters/Origin'
  /mailPieces/v2/summary:
    get:
      responses:
        '200':
          description: 200 OK
      parameters:
        - name: mailPieceId
          type: string
          required: true
          in: query
          description: Java web token which has a list of one or more tracking numbers of the mail item(s) being queried.
        - $ref: '#/parameters/X-RMG-Auth-Token'
        - $ref: '#/parameters/X-RMG-Language'
        - $ref: '#/parameters/Origin'
      description: Get summary information for a list of mailPieceIds
tags: []
basePath: /
parameters:
  X-RMG-Auth-Token:
    name: X-RMG-Auth-Token
    type: string
    required: true
    in: header
    description: 'Java Web Token generated by eBusiness, optional, passed when a user is logged in'
  X-RMG-Language:
    name: X-RMG-Language
    type: string
    required: false
    in: header
    description: "System defaults to english; alternative is 'Cymraeg', valid values 'en' and 'cy'"
  Origin:
    name: Origin
    type: string
    required: true
    in: header
    description: Origin is always supplied by the browser for this OPTIONS call
  X-recaptcha-response:
    name: X-recaptcha-response
    type: string
    required: false
    in: header
    description: 'Google Catpcha Token, originates from Google, passed by eBusiness, optional, passed'
  X-recaptcha-session:
    name: X-recaptcha-session
    type: string
    required: false
    in: header
    description: signed JWT
