info:
  x-ibm-name: local-collect-api-v2-soap
  version: 1.0.0-rev25
  description: >-
    Local Collect is a delivery enhancement to Royal Mail Tracked & Special
    Delivery Guaranteed products that enables customers to benefit from ‘Click
    and Collect’ options by having their parcels delivered to participating Post
    Offices and Royal Mail enquiry offices. The Local Collect API allows
    customers to retrieve an up-to-date list of Post Offices and Royal Mail
    Enquiry Offices, where the item can be held awaiting collection.



    _There are no costs to customers for using the Local Collect API services,
    however development costs must be covered by the customer. Royal Mail will
    not accept any responsibility for these development, implementation and
    testing costs._
  title: Local Collect API V2 (SOAP)
paths:
  /getLocations:
    post:
      x-ibm-soap:
        soap-action: 'http://royalmail.com/LocalCollectInterfacev3_0/getLocalCollectLocations'
        soap-operation: '{http://www.royalmailgroup.com/API/LocalCollect/schema/V2.0}getLocationsRequest'
      responses:
        '200':
          description: Generated Response Description
          examples:
            application/xml: >-
              <v2:getLocationsResponse
              xmlns:v2="http://www.royalmailgroup.com/API/LocalCollect/schema/V2.0">

                <!--Optional:-->

                <locations>

                  <!--0 to 20 repetitions:-->

                  <location>

                    <organisationName>string</organisationName>

                    <locationName>string</locationName>

                    <addressLine1>string</addressLine1>

                    <!--Optional:-->

                    <addressLine2>string</addressLine2>

                    <!--Optional:-->

                    <addressLine3>string</addressLine3>

                    <!--Optional:-->

                    <city>string</city>

                    <!--Optional:-->

                    <county>string</county>

                    <postcode>string</postcode>

                    <!--1 to 7 repetitions:-->

                    <openingHours>

                      <dayOfWeek>Friday</dayOfWeek>

                      <openingTime>06:36:28</openingTime>

                      <closingTime>18:44:14</closingTime>

                      <!--Optional:-->

                      <lunchHours>

                        <lunchClosingTime>05:36:46+00:00</lunchClosingTime>

                        <lunchOpeningTime>01:02:49+00:00</lunchOpeningTime>

                      </lunchHours>

                    </openingHours>

                    <geoLocation>

                      <latitude>1000.00</latitude>

                      <longitude>1000.00</longitude>

                    </geoLocation>

                    <distance>100</distance>

                    <!--Optional:-->

                    <facilities>

                      <customerParkingIndicator>true</customerParkingIndicator>

                      <disabilityIndicator>false</disabilityIndicator>

                    </facilities>

                    <locationType>Enquiry Office</locationType>

                  </location>

                </locations>

                <!--Optional:-->

                <integrationFooter>

                  <!--Optional:-->

                  <errors>

                    <!--Zero or more repetitions:-->

                    <error>

                      <errorCode>string</errorCode>

                      <errorDescription>string</errorDescription>

                      <!--Optional:-->

                      <errorCause>string</errorCause>

                      <!--Optional:-->

                      <errorResolution>string</errorResolution>

                      <!--Optional:-->

                      <errorContext>string</errorContext>

                    </error>

                  </errors>

                  <!--Optional:-->

                  <warnings>

                    <!--Zero or more repetitions:-->

                    <warning>

                      <warningCode>string</warningCode>

                      <warningDescription>string</warningDescription>

                      <!--Optional:-->

                      <warningCause>string</warningCause>

                      <!--Optional:-->

                      <warningResolution>string</warningResolution>

                      <!--Optional:-->

                      <warningContext>string</warningContext>

                    </warning>

                  </warnings>

                </integrationFooter>

              </v2:getLocationsResponse>
      description: ''
      parameters:
        - schema:
            type: object
            example: >-
              <SOAP-ENV:Envelope
              xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header><v3:integrationHeader
              xmlns:v3="http://www.royalmailgroup.com/integration/core/V3">

                <!--Optional:-->

                <dateTime>2008-09-29T01:49:45</dateTime>

                <!--Optional:-->

                <version>1000.00</version>

                <identification>

                  <!--Optional:-->

                  <endUserId>string</endUserId>

                  <!--Optional:-->

                  <clientId>string</clientId>

                  <applicationId>string</applicationId>

                  <!--Optional:-->

                  <intermediaryId>string</intermediaryId>

                  <transactionId>string</transactionId>

                </identification>

                <!--Optional:-->

                <debugAudit>

                  <!--Optional:-->

                  <testFlag>true</testFlag>

                  <!--Optional:-->

                  <debugFlag>true</debugFlag>

                  <!--Optional:-->

                  <performanceFlag>true</performanceFlag>

                  <!--Optional:-->

                  <messageAuditFlag>true</messageAuditFlag>

                </debugAudit>

              </v3:integrationHeader></SOAP-ENV:Header><SOAP-ENV:Body><v2:getLocationsReques
               xmlns:v2="http://www.royalmailgroup.com/API/LocalCollect/schema/V2.0">

                <!--You have a CHOICE of the next 2 items at this level-->

                <postCode>string</postCode>

                <geoLocation>

                  <latitude>1000.00</latitude>

                  <longitude>1000.00</longitude>

                </geoLocation>

                <!--Optional:-->

                <locationType>Enquiry Office</locationType>

                <!--Optional:-->

                <radius>20</radius>

              </v2:getLocationsRequest></SOAP-ENV:Body></SOAP-ENV:Envelope>
          required: true
          name: body
          in: body
      operationId: getLocations
schemes:
  - https
tags: []
basePath: /localcollect/v2
produces:
  - application/xml
x-ibm-configuration:
  enforced: true
  catalogs: {}
  externalDocs: []
  gateway: datapower-gateway
  type: wsdl
  cors:
    enabled: true
  phase: realized
  assembly:
    execute:
      - operation-switch:
          case:
            - operations:
                - getLocations
              execute:
                - activity-log:
                    content: $(Activity Log Level)
                    error-content: $(Error Log Level)
                    title: activity-log
                - proxy:
                    cache-ttl: 900
                    stop-on-error:
                      - ConnectionError
                      - SOAPError
                      - OperationError
                    title: proxy
                    tls-profile: $(Certificate Name)
                    target-url: $(Local Collect Endpoint)
                    verb: keep
                    cache-response: protocol
                    timeout: 60
          otherwise: []
          title: operation-switch
  wsdl-definition:
    wsdl: local-collect-api-v2-soap_1.0.0-rev25.zip
    soap-version: '1.1'
    port: ''
    service: LocalCollectServicev2_0
  testable: true
  properties:
    Local Collect Endpoint:
      encoded: false
      description: This is the Local Collect end point
      value: 'https://live-api.royalmail.com/localcollect/v2'
    Certificate Name:
      encoded: false
      description: Default Certificate Name
      value: live-ca2
    Activity Log Level:
      encoded: false
      description: 'What to log per api call. Choices are none, activity, header, payload'
      value: payload
    Error Log Level:
      encoded: false
      description: 'What to log per api error. Choices are none, activity, header, payload'
      value: payload
securityDefinitions:
  Client ID:
    description: ''
    type: apiKey
    name: X-IBM-Client-Id
    in: header
definitions: {}
security:
  - Client ID: []
swagger: '2.0'
consumes:
  - text/xml
